/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import data.DataAccess;
import javax.swing.table.AbstractTableModel;
import principal.tablemodels.IntentosUsuario;

/**
 *
 * @author Ziku
 */
public class InformacionUsuario extends javax.swing.JDialog {

    private Main main;
    private DataAccess da = new DataAccess();
    
    
    
    public InformacionUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        main = (Main)parent;
        int seleccion = main.SeleccionFilaUsuariosIntentos();
        initComponents();
        String idS = String.valueOf(da.getAllUsers().get(seleccion).getId());
        lbl_IDRespuesta.setText(idS);
        lbl_NombreRespuesta.setText(da.getAllUsers().get(seleccion).getNombre());
        lbl_EmailRespuesta.setText(da.getAllUsers().get(seleccion).getEmail());
        tbl_IntentosUsuario.setModel(new IntentosUsuario(da.getAttemptsPerUser(da.getAllUsers().get(seleccion))));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_idEnunciado = new javax.swing.JLabel();
        lbl_NombreEnunciado = new javax.swing.JLabel();
        lbl_EmailEnunciado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_IntentosUsuario = new javax.swing.JTable();
        lbl_IDRespuesta = new javax.swing.JLabel();
        lbl_NombreRespuesta = new javax.swing.JLabel();
        lbl_EmailRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_idEnunciado.setText("ID:");

        lbl_NombreEnunciado.setText("Nombre:");

        lbl_EmailEnunciado.setText("Email:");

        tbl_IntentosUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_IntentosUsuario);

        lbl_IDRespuesta.setText("jLabel5");

        lbl_NombreRespuesta.setText("jLabel6");

        lbl_EmailRespuesta.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_idEnunciado)
                            .addComponent(lbl_NombreEnunciado)
                            .addComponent(lbl_EmailEnunciado))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_EmailRespuesta)
                            .addComponent(lbl_NombreRespuesta)
                            .addComponent(lbl_IDRespuesta))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idEnunciado)
                    .addComponent(lbl_IDRespuesta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NombreEnunciado)
                    .addComponent(lbl_NombreRespuesta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmailEnunciado)
                    .addComponent(lbl_EmailRespuesta))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InformacionUsuario dialog = new InformacionUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_EmailEnunciado;
    private javax.swing.JLabel lbl_EmailRespuesta;
    private javax.swing.JLabel lbl_IDRespuesta;
    private javax.swing.JLabel lbl_NombreEnunciado;
    private javax.swing.JLabel lbl_NombreRespuesta;
    private javax.swing.JLabel lbl_idEnunciado;
    private javax.swing.JTable tbl_IntentosUsuario;
    // End of variables declaration//GEN-END:variables
}
