/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import com.mycompany.customcomponentejercicio.SwipeListener;
import data.DataAccess;
import dto.Intent;
import dto.Review;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ziku
 */
public class InformacionUsuario extends javax.swing.JDialog {

    private Main main;
    private DataAccess da = new DataAccess();
    private int seleccion;
    private ArrayList<Intent> intentosUsuario = new ArrayList<>();
    private String direccion;
    private int idEjer;

    public InformacionUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        main = (Main) parent;
        seleccion = main.SeleccionFilaUsuariosIntentos();
        initComponents();
        btn_EditarReview.setEnabled(false);
        btn_EliminarReview.setEnabled(false);
        btn_RevisarReview.setEnabled(false);
        String idS = String.valueOf(da.getAllUsers().get(seleccion).getId());
        lbl_IDRespuesta.setText(idS);
        lbl_NombreRespuesta.setText(da.getAllUsers().get(seleccion).getNombre());
        lbl_EmailRespuesta.setText(da.getAllUsers().get(seleccion).getEmail());
        conseguirIntentosUsuario();
    }

    public int getIDReview(int idIntento) {
        int idReview = da.getAttemptReview(idIntento).getId();
        return idReview;
    }

    public int getIDIntento() {
        Intent intentoUsuario = buscarIntentoUsuario(idEjer);
        return intentoUsuario.getId();
    }

    public void conseguirIntentosUsuario() {
        intentosUsuario = da.getAttemptsPerUser(da.getAllUsers().get(seleccion));

        for (Intent intent : intentosUsuario) {
            com.mycompany.customcomponentejercicio.CustomComponentEjercicio pnl_customComponentEjercicio = new com.mycompany.customcomponentejercicio.CustomComponentEjercicio();
            pnl_customComponentEjercicio.setnombreEjercicio(intent.getNombreEjercicio());
            pnl_customComponentEjercicio.setnombreUsuario(intent.getNombreUsuario());
            pnl_customComponentEjercicio.setfechaIntento(intent.getTimestamp_Inicio());
            pnl_customComponentEjercicio.setIdEjercicio(intent.getIdEjercicio());
            int idreview = getIDReview(intent.getId());
            if (idreview == 0) {
                pnl_customComponentEjercicio.setestadoIntento(1);
            } else {
                pnl_customComponentEjercicio.setestadoIntento(2);
            }
            pnl_ejerciciosUsuario.add(pnl_customComponentEjercicio);
            pnl_customComponentEjercicio.setFocusable(true);
            pnl_customComponentEjercicio.addSwipeListener(new SwipeListener() {
                @Override
                public void arrastrar(String dirrecion, int idEjercicio) {
                    direccion = dirrecion;
                    idEjer = idEjercicio;
                    String videoFile = "";
                    if (direccion.equals("right")) {
                        Intent intentoUsuario = buscarIntentoUsuario(idEjer);
                        if (intentoUsuario != null) {
                            videoFile = intentoUsuario.getVideofile();
                        }
                        main.video(videoFile);
                        dispose();
                    }
                    if (direccion.equals("left")) {
                        btn_RevisarReview.setEnabled(true);
                        btn_EliminarReview.setEnabled(true);
                        btn_EditarReview.setEnabled(true);
                    }
                }
            });
            
        }

    }

    private void IniciarRevisionReview() {
        RevisionReview revisionReview = new RevisionReview(this, true);
        revisionReview.setVisible(true);
    }

    private void noReview() {
        JOptionPane.showMessageDialog(this, "No exite la review de este intento");
    }

    public void ActualizarIntentosUsuario() {
        pnl_ejerciciosUsuario.removeAll();
        conseguirIntentosUsuario();
        dispose();
    }

    public Intent buscarIntentoUsuario(int idEjer) {
        for (Intent intento : intentosUsuario) {
            int id = intento.getIdEjercicio();
            if (id == idEjer) {
                return intento;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_idEnunciado = new javax.swing.JLabel();
        lbl_NombreEnunciado = new javax.swing.JLabel();
        lbl_EmailEnunciado = new javax.swing.JLabel();
        lbl_IDRespuesta = new javax.swing.JLabel();
        lbl_NombreRespuesta = new javax.swing.JLabel();
        lbl_EmailRespuesta = new javax.swing.JLabel();
        btn_RevisarReview = new javax.swing.JButton();
        btn_EditarReview = new javax.swing.JButton();
        btn_EliminarReview = new javax.swing.JButton();
        pnl_ejerciciosUsuario = new javax.swing.JPanel();
        lbl_verVideo = new javax.swing.JLabel();
        lbl_activarBotones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion del Usuario");
        setResizable(false);
        setSize(new java.awt.Dimension(464, 391));

        lbl_idEnunciado.setText("ID:");

        lbl_NombreEnunciado.setText("Nombre:");

        lbl_EmailEnunciado.setText("Email:");

        lbl_IDRespuesta.setText("jLabel5");

        lbl_NombreRespuesta.setText("jLabel6");

        lbl_EmailRespuesta.setText("jLabel7");

        btn_RevisarReview.setText("Revisar Review");
        btn_RevisarReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RevisarReviewActionPerformed(evt);
            }
        });

        btn_EditarReview.setText("Editar Review");
        btn_EditarReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarReviewActionPerformed(evt);
            }
        });

        btn_EliminarReview.setText("Eliminar Review");
        btn_EliminarReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarReviewActionPerformed(evt);
            }
        });

        pnl_ejerciciosUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_ejerciciosUsuario.setPreferredSize(new java.awt.Dimension(380, 316));
        pnl_ejerciciosUsuario.setLayout(new javax.swing.BoxLayout(pnl_ejerciciosUsuario, javax.swing.BoxLayout.PAGE_AXIS));

        lbl_verVideo.setText("Ver Video (Desliza) -->");

        lbl_activarBotones.setText("<--(Desliza) Activar botones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_activarBotones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_verVideo)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_EliminarReview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_EditarReview)
                                .addGap(47, 47, 47)
                                .addComponent(btn_RevisarReview))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnl_ejerciciosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_idEnunciado)
                                        .addComponent(lbl_NombreEnunciado)
                                        .addComponent(lbl_EmailEnunciado))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_EmailRespuesta)
                                        .addComponent(lbl_NombreRespuesta)
                                        .addComponent(lbl_IDRespuesta)))))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idEnunciado)
                    .addComponent(lbl_IDRespuesta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NombreEnunciado)
                    .addComponent(lbl_NombreRespuesta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmailEnunciado)
                    .addComponent(lbl_EmailRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_ejerciciosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EditarReview)
                    .addComponent(btn_RevisarReview)
                    .addComponent(btn_EliminarReview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_verVideo)
                    .addComponent(lbl_activarBotones))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btn_RevisarReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RevisarReviewActionPerformed
        Intent intentoUsuario = buscarIntentoUsuario(idEjer);
        int id = intentoUsuario.getId();
        if (getIDReview(id) != 0) {
            IniciarRevisionReview();
        } else {
            noReview();
        }
    }//GEN-LAST:event_btn_RevisarReviewActionPerformed

    private void btn_EditarReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarReviewActionPerformed
        Intent intentoUsuario = buscarIntentoUsuario(idEjer);
        int id = intentoUsuario.getId();
        if (getIDReview(id) != 0) {
            RevalorarIntento revalorarIntento = new RevalorarIntento(this, true);
            revalorarIntento.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No exite la review de este intento");
        }
    }//GEN-LAST:event_btn_EditarReviewActionPerformed

    private void btn_EliminarReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarReviewActionPerformed
        Intent intentoUsuario = buscarIntentoUsuario(idEjer);
        int id = intentoUsuario.getId();
        Review eliminarReview = da.getAttemptReview(id);
        da.dropReview(eliminarReview.getId());
        ActualizarIntentosUsuario();
        main.ActualizarCambiosIntentosPendientes();
        JOptionPane.showMessageDialog(this, "Se ha eliminado la review correctamente");


    }//GEN-LAST:event_btn_EliminarReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditarReview;
    private javax.swing.JButton btn_EliminarReview;
    private javax.swing.JButton btn_RevisarReview;
    private javax.swing.JLabel lbl_EmailEnunciado;
    private javax.swing.JLabel lbl_EmailRespuesta;
    private javax.swing.JLabel lbl_IDRespuesta;
    private javax.swing.JLabel lbl_NombreEnunciado;
    private javax.swing.JLabel lbl_NombreRespuesta;
    private javax.swing.JLabel lbl_activarBotones;
    private javax.swing.JLabel lbl_idEnunciado;
    private javax.swing.JLabel lbl_verVideo;
    private javax.swing.JPanel pnl_ejerciciosUsuario;
    // End of variables declaration//GEN-END:variables
}
