/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import at.favre.lib.crypto.bcrypt.BCrypt;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import data.DataAccess;
import dto.Usuari;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ziku
 */
public class Login extends javax.swing.JDialog {

    private boolean conectado = false;
    private DataAccess da = new DataAccess();
    private Usuari user;
    private Main main;
    private boolean segundaConexion;

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal, Usuari user, boolean segundaConexion) {
        super(parent, modal);
        main = (Main) parent;
        this.user = user;
        initComponents();
        conectado = false;
        this.segundaConexion = segundaConexion;
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        
        
        });

    }

    public boolean EstasConectado() {
        return conectado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TextoIniciarSesion = new javax.swing.JLabel();
        lbl_CorreoElectronico = new javax.swing.JLabel();
        txt_PonerMail = new javax.swing.JTextField();
        lbl_Contraseña = new javax.swing.JLabel();
        btn_IniciarSesion = new javax.swing.JToggleButton();
        txt_PonerContraseña = new javax.swing.JPasswordField();
        lbl_clickParaRegistrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(539, 310));

        lbl_TextoIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_TextoIniciarSesion.setText("Inicio de Sesión");

        lbl_CorreoElectronico.setText("Correo Electrónico");

        lbl_Contraseña.setText("Contraseña:");

        btn_IniciarSesion.setText("Iniciar Sesion");
        btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarSesionActionPerformed(evt);
            }
        });

        txt_PonerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PonerContraseñaActionPerformed(evt);
            }
        });

        lbl_clickParaRegistrar.setText("No tienes cuenta? Pulsa aqui para registrarte.");
        lbl_clickParaRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btn_IniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_clickParaRegistrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_TextoIniciarSesion)
                                .addComponent(lbl_Contraseña)
                                .addComponent(lbl_CorreoElectronico)
                                .addComponent(txt_PonerMail)
                                .addComponent(txt_PonerContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_TextoIniciarSesion)
                .addGap(45, 45, 45)
                .addComponent(lbl_CorreoElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PonerMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PonerContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_IniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(lbl_clickParaRegistrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarSesionActionPerformed
        user = da.getUser(txt_PonerMail.getText());
        try {
            if (user != null) {

                char[] contraseñaParaVerificar = txt_PonerContraseña.getPassword();
                String contraseñaEnBaseDatos = user.getPasswordHash();
                var resultado = BCrypt.verifyer().verify(contraseñaParaVerificar, contraseñaEnBaseDatos);
                if (resultado.verified) {
                    JOptionPane.showMessageDialog(this, "Sesion iniciada. Bienvenido " + user.getNombre());
                    dispose();
                    main.UsuarioConectado(user);
                    conectado = true;
                    if(segundaConexion){
                    main.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Acceso denegado: Contraseña incorrecta");
                }

            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Acceso denegado: El usuario no exite");
        }
    }//GEN-LAST:event_btn_IniciarSesionActionPerformed

    private void txt_PonerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PonerContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PonerContraseñaActionPerformed

    private void lbl_clickParaRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseClicked
        Register registrarse = new Register(this, true);
        registrarse.setVisible(true);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseClicked

    private void lbl_clickParaRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseEntered
        lbl_clickParaRegistrar.setForeground(Color.blue);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseEntered

    private void lbl_clickParaRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseExited
        lbl_clickParaRegistrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_IniciarSesion;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_CorreoElectronico;
    private javax.swing.JLabel lbl_TextoIniciarSesion;
    private javax.swing.JLabel lbl_clickParaRegistrar;
    private javax.swing.JPasswordField txt_PonerContraseña;
    private javax.swing.JTextField txt_PonerMail;
    // End of variables declaration//GEN-END:variables
}
