/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import at.favre.lib.crypto.bcrypt.BCrypt;
import data.DataAccess;
import dto.Usuari;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ziku
 */
public class Login extends javax.swing.JDialog {

    private boolean conectado = false;
    private DataAccess da = new DataAccess();
    private Usuari user;
    private Main main;
    private boolean segundaConexion;

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal, Usuari user, boolean segundaConexion) {
        super(parent, modal);
        main = (Main) parent;
        this.user = user;
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/logoIcono.jpg"));
        setIconImage(icono);
        btn_IniciarSesion.setBackground(Color.white);
        conectado = false;
        this.segundaConexion = segundaConexion;
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        
        
        });

    }

    public boolean EstasConectado() {
        return conectado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_colorVentana = new javax.swing.JPanel();
        lbl_TextoIniciarSesion = new javax.swing.JLabel();
        lbl_CorreoElectronico = new javax.swing.JLabel();
        txt_PonerMail = new javax.swing.JTextField();
        lbl_Contraseña = new javax.swing.JLabel();
        btn_IniciarSesion = new javax.swing.JToggleButton();
        txt_PonerContraseña = new javax.swing.JPasswordField();
        lbl_clickParaRegistrar = new javax.swing.JLabel();
        lbl_logoPrograma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setResizable(false);
        setSize(new java.awt.Dimension(539, 310));

        pnl_colorVentana.setBackground(new java.awt.Color(51, 51, 51));

        lbl_TextoIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_TextoIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TextoIniciarSesion.setText("Inicio de Sesión");

        lbl_CorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_CorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CorreoElectronico.setText("Correo Electrónico:");

        lbl_Contraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Contraseña.setText("Contraseña:");

        btn_IniciarSesion.setText("Iniciar Sesion");
        btn_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_IniciarSesionMouseReleased(evt);
            }
        });
        btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarSesionActionPerformed(evt);
            }
        });
        btn_IniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_IniciarSesionKeyReleased(evt);
            }
        });

        txt_PonerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PonerContraseñaActionPerformed(evt);
            }
        });

        lbl_clickParaRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clickParaRegistrar.setText("Nuevo Profesor? Pulsa aqui para registrarte.");
        lbl_clickParaRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_clickParaRegistrarMouseExited(evt);
            }
        });

        lbl_logoPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fitnow.jpg"))); // NOI18N
        lbl_logoPrograma.setText("jLabel1");

        javax.swing.GroupLayout pnl_colorVentanaLayout = new javax.swing.GroupLayout(pnl_colorVentana);
        pnl_colorVentana.setLayout(pnl_colorVentanaLayout);
        pnl_colorVentanaLayout.setHorizontalGroup(
            pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                        .addComponent(lbl_clickParaRegistrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                        .addGroup(pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_TextoIniciarSesion)
                                .addComponent(lbl_Contraseña)
                                .addComponent(lbl_CorreoElectronico)
                                .addComponent(txt_PonerMail)
                                .addComponent(txt_PonerContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn_IniciarSesion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(lbl_logoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        pnl_colorVentanaLayout.setVerticalGroup(
            pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                .addGroup(pnl_colorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_TextoIniciarSesion)
                        .addGap(45, 45, 45)
                        .addComponent(lbl_CorreoElectronico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_PonerMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Contraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_PonerContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_IniciarSesion))
                    .addGroup(pnl_colorVentanaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbl_logoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbl_clickParaRegistrar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_colorVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_colorVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_clickParaRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseExited
        lbl_clickParaRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseExited

    private void lbl_clickParaRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseEntered
        lbl_clickParaRegistrar.setForeground(Color.cyan);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseEntered

    private void lbl_clickParaRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clickParaRegistrarMouseClicked
        Register registrarse = new Register(this, true);
        registrarse.setVisible(true);
    }//GEN-LAST:event_lbl_clickParaRegistrarMouseClicked

    private void txt_PonerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PonerContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PonerContraseñaActionPerformed

    private void btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarSesionActionPerformed
        user = da.getUser(txt_PonerMail.getText());
        try {
            if (user != null) {

                char[] contraseñaParaVerificar = txt_PonerContraseña.getPassword();
                String contraseñaEnBaseDatos = user.getPasswordHash();
                var resultado = BCrypt.verifyer().verify(contraseñaParaVerificar, contraseñaEnBaseDatos);
                if (resultado.verified) {
                    JOptionPane.showMessageDialog(this, "Sesion iniciada. Bienvenido " + user.getNombre());
                    dispose();
                    main.UsuarioConectado(user);
                    conectado = true;
                    if(segundaConexion){
                        main.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Acceso denegado: Contraseña incorrecta");
                }

            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Acceso denegado: El usuario no exite");
        }
    }//GEN-LAST:event_btn_IniciarSesionActionPerformed

    private void btn_IniciarSesionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_IniciarSesionKeyReleased

    }//GEN-LAST:event_btn_IniciarSesionKeyReleased

    private void btn_IniciarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMouseReleased
        btn_IniciarSesion.setBackground(Color.white);
    }//GEN-LAST:event_btn_IniciarSesionMouseReleased

    private void btn_IniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMousePressed
        btn_IniciarSesion.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btn_IniciarSesionMousePressed

    private void btn_IniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMouseEntered
        Color azulPastel = new Color(173,216,230); 
        btn_IniciarSesion.setBackground(azulPastel);
    }//GEN-LAST:event_btn_IniciarSesionMouseEntered

    private void btn_IniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarSesionMouseExited
        btn_IniciarSesion.setBackground(Color.white);
    }//GEN-LAST:event_btn_IniciarSesionMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_IniciarSesion;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_CorreoElectronico;
    private javax.swing.JLabel lbl_TextoIniciarSesion;
    private javax.swing.JLabel lbl_clickParaRegistrar;
    private javax.swing.JLabel lbl_logoPrograma;
    private javax.swing.JPanel pnl_colorVentana;
    private javax.swing.JPasswordField txt_PonerContraseña;
    private javax.swing.JTextField txt_PonerMail;
    // End of variables declaration//GEN-END:variables
}
