/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import at.favre.lib.crypto.bcrypt.BCrypt;
import data.DataAccess;
import dto.Usuari;
import javax.swing.JOptionPane;

/**
 *
 * @author Ziku
 */
public class Register extends javax.swing.JDialog {
    
    /**
     * Creates new form Register
     */
    public Register(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();      
    }
    //Validador para que no haya erores a la hora de introducir los datos
    private boolean ValidarCampos(){
     String nombre = txt_ponerNombre.getText();
     String email = txt_ponerCorreo.getText();
     char [] contraseña = txt_contraseña.getPassword();
     if(nombre == null || "".equals(nombre)){
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
     } else if (email == null || "".equals(email) ){
         JOptionPane.showMessageDialog(this, "El correo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
         return false;
     } else if (contraseña.length <= 0){ //Le faltan unos ajustes
         JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacia", "Error", JOptionPane.ERROR_MESSAGE);
         return false;
     } else
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Register = new javax.swing.JPanel();
        lbl_nombreRegis = new javax.swing.JLabel();
        txt_ponerNombre = new javax.swing.JTextField();
        lbl_correoElectronicoRegis = new javax.swing.JLabel();
        txt_ponerCorreo = new javax.swing.JTextField();
        lbl_contraseñaRegis = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        chk_instructor = new javax.swing.JCheckBox();
        btn_registrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar nuevo usuario");

        pnl_Register.setBorder(javax.swing.BorderFactory.createTitledBorder("Register"));

        lbl_nombreRegis.setText("Nombre");

        txt_ponerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ponerNombreActionPerformed(evt);
            }
        });

        lbl_correoElectronicoRegis.setText("Correo Electrónico");

        txt_ponerCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ponerCorreoActionPerformed(evt);
            }
        });

        lbl_contraseñaRegis.setText("Contraseña");

        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });

        chk_instructor.setText("Eres instructor?");
        chk_instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_instructorActionPerformed(evt);
            }
        });

        btn_registrarse.setText("Registrarse");
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_RegisterLayout = new javax.swing.GroupLayout(pnl_Register);
        pnl_Register.setLayout(pnl_RegisterLayout);
        pnl_RegisterLayout.setHorizontalGroup(
            pnl_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RegisterLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_contraseña)
                        .addComponent(lbl_contraseñaRegis)
                        .addComponent(lbl_nombreRegis)
                        .addComponent(lbl_correoElectronicoRegis)
                        .addComponent(txt_ponerCorreo)
                        .addComponent(txt_ponerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk_instructor))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registrarse)
                .addGap(46, 46, 46))
        );
        pnl_RegisterLayout.setVerticalGroup(
            pnl_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RegisterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_nombreRegis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ponerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_correoElectronicoRegis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ponerCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_contraseñaRegis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(chk_instructor)
                .addGap(25, 25, 25)
                .addComponent(btn_registrarse)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ponerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ponerNombreActionPerformed

    }//GEN-LAST:event_txt_ponerNombreActionPerformed

    private void chk_instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_instructorActionPerformed

    }//GEN-LAST:event_chk_instructorActionPerformed

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        if (ValidarCampos()){
        Usuari nuevoUsuario = new Usuari();
        nuevoUsuario.setNombre(txt_ponerNombre.getText());
        nuevoUsuario.setEmail(txt_ponerCorreo.getText());
        String contraseñaZifrada = BCrypt.withDefaults().hashToString(12, txt_contraseña.getPassword());
        nuevoUsuario.setPasswordHash(contraseñaZifrada);
        nuevoUsuario.setInstructor(chk_instructor.isSelected());
        
        DataAccess da = new DataAccess();
        int idNuevoUsuario = da.registerUser(nuevoUsuario);
        nuevoUsuario.setId(idNuevoUsuario);
        JOptionPane.showMessageDialog(this, "El usuario se ha registrado de manera correcta" );
        setVisible(false); 
        }
    }//GEN-LAST:event_btn_registrarseActionPerformed

    private void txt_ponerCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ponerCorreoActionPerformed
     
    }//GEN-LAST:event_txt_ponerCorreoActionPerformed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JCheckBox chk_instructor;
    private javax.swing.JLabel lbl_contraseñaRegis;
    private javax.swing.JLabel lbl_correoElectronicoRegis;
    private javax.swing.JLabel lbl_nombreRegis;
    private javax.swing.JPanel pnl_Register;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_ponerCorreo;
    private javax.swing.JTextField txt_ponerNombre;
    // End of variables declaration//GEN-END:variables
}
