/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package principal;

import data.DataAccess;

/**
 *
 * @author Ziku
 */
public class RevisionReview extends javax.swing.JDialog {

    private InformacionUsuario infoUsuario;
    private DataAccess da = new DataAccess();

    /**
     * Creates new form RevisionReview
     */
    public RevisionReview(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        infoUsuario = (InformacionUsuario) parent;
        initComponents();

        lbl_suspendido.setVisible(false);
        int idIntento = infoUsuario.getIDIntento();
        String idStringIntento = String.valueOf(idIntento);
        lbl_IDintentoRespuesta.setText(idStringIntento);
        String idReviewer = String.valueOf(da.getAttemptReview(idIntento).getIdReviewer());
        lbl_IDReviewerRespuesta.setText(idReviewer);
        String idReview = String.valueOf(da.getAttemptReview(idIntento).getId());
        lbl_IDReviewRespuesta.setText(idReview);
        String valoracion = String.valueOf(da.getAttemptReview(idIntento).getValoracion());
        lbl_ValoracionRespuesta.setText(valoracion);
        txa_ComentarioRespuesta.setText(da.getAttemptReview(idIntento).getComentario());
        if (da.getAttemptReview(idIntento).getValoracion() < 3) {
            lbl_suspendido.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IDReviewEnunciado = new javax.swing.JLabel();
        lbl_IDReviewerEnunciado = new javax.swing.JLabel();
        lbl_ValoracionEnunciado = new javax.swing.JLabel();
        lbl_IDIntentoEnunciado = new javax.swing.JLabel();
        lbl_ComentarioEnunciado = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        txa_ComentarioRespuesta = new javax.swing.JTextArea();
        lbl_IDReviewRespuesta = new javax.swing.JLabel();
        lbl_IDReviewerRespuesta = new javax.swing.JLabel();
        lbl_IDintentoRespuesta = new javax.swing.JLabel();
        lbl_ValoracionRespuesta = new javax.swing.JLabel();
        lbl_suspendido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Revision de la Review");
        setResizable(false);
        setSize(new java.awt.Dimension(471, 300));

        lbl_IDReviewEnunciado.setText("ID de la Review:");

        lbl_IDReviewerEnunciado.setText("ID del Reviewer:");

        lbl_ValoracionEnunciado.setText("Valoracion:");

        lbl_IDIntentoEnunciado.setText("ID del Intento:");

        lbl_ComentarioEnunciado.setText("Comentario:");

        txa_ComentarioRespuesta.setColumns(20);
        txa_ComentarioRespuesta.setRows(5);
        ScrollPane.setViewportView(txa_ComentarioRespuesta);

        lbl_IDReviewRespuesta.setText("jLabel1");

        lbl_IDReviewerRespuesta.setText("jLabel2");

        lbl_IDintentoRespuesta.setText("jLabel3");

        lbl_ValoracionRespuesta.setText("jLabel4");

        lbl_suspendido.setForeground(new java.awt.Color(255, 51, 51));
        lbl_suspendido.setText("Tienes que repetir el intento no has aprobado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_IDReviewerEnunciado)
                                    .addComponent(lbl_IDReviewEnunciado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_IDReviewRespuesta)
                                    .addComponent(lbl_IDReviewerRespuesta)))
                            .addComponent(lbl_ComentarioEnunciado))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_suspendido)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_ValoracionEnunciado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_ValoracionRespuesta))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_IDIntentoEnunciado)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_IDintentoRespuesta))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDReviewEnunciado)
                    .addComponent(lbl_IDIntentoEnunciado)
                    .addComponent(lbl_IDReviewRespuesta)
                    .addComponent(lbl_IDintentoRespuesta))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDReviewerEnunciado)
                    .addComponent(lbl_ValoracionEnunciado)
                    .addComponent(lbl_IDReviewerRespuesta)
                    .addComponent(lbl_ValoracionRespuesta))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ComentarioEnunciado)
                    .addComponent(lbl_suspendido))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel lbl_ComentarioEnunciado;
    private javax.swing.JLabel lbl_IDIntentoEnunciado;
    private javax.swing.JLabel lbl_IDReviewEnunciado;
    private javax.swing.JLabel lbl_IDReviewRespuesta;
    private javax.swing.JLabel lbl_IDReviewerEnunciado;
    private javax.swing.JLabel lbl_IDReviewerRespuesta;
    private javax.swing.JLabel lbl_IDintentoRespuesta;
    private javax.swing.JLabel lbl_ValoracionEnunciado;
    private javax.swing.JLabel lbl_ValoracionRespuesta;
    private javax.swing.JLabel lbl_suspendido;
    private javax.swing.JTextArea txa_ComentarioRespuesta;
    // End of variables declaration//GEN-END:variables
}
